service: lambda-image-viewer

provider:
  name: aws
  runtime: go1.x # TODO
  memorySize: 256

  region: ${env:REGION}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:GetItem"
        - "dynamodb:BatchGetItem"
        - "dynamodb:Scan"
        - "dynamodb:Query"
        - "dynamodb:ConditionCheckItem"
        - "dynamodb:BatchGetItem"
        - "dynamodb:BatchWriteItem"
        - "dynamodb:PutItem"
        - "dynamodb:DescribeTable"
        - "dynamodb:DeleteItem"
        - "dynamodb:UpdateItem"
      Resource: "*"

package:
  individually: true

functions:
  viewer:
    handler: bin/viewer
    url: true
    environment:
      REGION: ${env:REGION}
      ORIGIN_DOMAIN: ${env:ORIGIN_DOMAIN}
      TABLE: "${env:ORIGIN_DOMAIN}-item"
    package:
      include:
        - bin/viewer

  tagger:
    handler: bin/tagger
    url: false
    environment:
      REGION: ${env:REGION}
      TABLE: "${env:ORIGIN_DOMAIN}-item"
    package:
      include:
        - bin/tagger
    events:
      - s3:
          bucket: ${env:ORIGIN_DOMAIN}
          event: "s3:ObjectCreated:*"
          rules:
            - suffix: .jpg
          existing: true

useDotenv: true
