service: lambda-image-viewer

provider:
  name: aws
  runtime: go1.x # TODO
  memorySize: 256

  region: ${env:REGION}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:GetItem"
        - "dynamodb:BatchGetItem"
        - "dynamodb:Scan"
        - "dynamodb:Query"
        - "dynamodb:ConditionCheckItem"
        - "dynamodb:BatchGetItem"
        - "dynamodb:BatchWriteItem"
        - "dynamodb:PutItem"
        - "dynamodb:DescribeTable"
        - "dynamodb:DeleteItem"
        - "dynamodb:UpdateItem"
      Resource: "*"

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  main:
    handler: bin/main
    url: true
    environment:
      REGION: ${env:REGION}
      ORIGIN_DOMAIN: ${env:ORIGIN_DOMAIN}
      TABLE: "${env:ORIGIN_DOMAIN}-item"

useDotenv: true
